# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'

    - name: Build with Maven
      run: cd hello-world/ && mvn -B package --file pom.xml
    
    - name: Test with Maven
      run: cd hello-world/ && mvn -B test --file pom.xml

    - run: pwd
    
    - name: find the jar
      run: find hello-docker-world-0.0.1-SNAPSHOT.jar

      
    # Build & Push Docker Image
#     - name: Set up QEMU
#       uses: docker/setup-qemu-action@v1
#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v1
#     - name: Login to DockerHub
#       uses: docker/login-action@v1 
#       with:
#         username: ${{ secrets.DOCKERHUB_USERNAME }}
#         password: ${{ secrets.DOCKERHUB_PASSWORD }}
#     - name: Build and push
#       uses: docker/build-push-action@v2
#       with:
#         push: true
#         tags: user/hello-world:latest
